# Generated by Django 2.0 on 2018-04-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180411_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')]),
        ),
    ]
