# Generated by Django 2.0 on 2018-04-10 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180411_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default=datetime.date(2018, 4, 11), verbose_name='出生日期'),
        ),
    ]
