# Generated by Django 2.0 on 2018-04-10 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180411_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default=datetime.date(2018, 4, 11), verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.IntegerField(blank=True, choices=[(1, '高中或以下学历'), (2, '学士'), (3, '硕士'), (4, '博士'), (5, '博士后')], verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.CharField(blank=True, max_length=100, verbose_name='爱好'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/static/blog/portrait/default.png', upload_to='portrait', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.CharField(blank=True, max_length=200, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=20, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
    ]
