# Generated by Django 2.0 on 2018-04-11 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20180411_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
