# Generated by Django 2.0 on 2018-04-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesdetail',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
